2022-08-15 15:14:58.845 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:15:03.613 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:15:03.613 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:15:03.613 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:16:18.849 | ERROR    | grpc_opentracing.grpcext._interceptor:handler:269 - An error has been caught in function 'handler', process 'MainProcess' (92033), thread 'ThreadPoolExecutor-0_0' (123145633210368):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fb0330e9c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145633210368)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fb0330e9940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145633210368)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145633210368)>
    │    │        │    └ (<weakref at 0x7fb035b48d10; to 'ThreadPoolExecutor' at 0x7fb035adcf10>, <_queue.SimpleQueue object at 0x7fb035af6220>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145633210368)>
    │    └ <function _worker at 0x7fb035b005e0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145633210368)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fb035b00430>
    └ <concurrent.futures.thread._WorkItem object at 0x7fb035b69520>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fb035b69520>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fb035b57040>, <grpc._server._RPCState object at 0x7fb035b4ff10>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fb035b69520>
             │    └ <function _unary_response_in_pool at 0x7fb035b2dee0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fb035b69520>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fb035b6c1f0>
                        │              │          └ <grpc._server._RPCState object at 0x7fb035b4ff10>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fb035b57040>
                        └ <function _call_behavior at 0x7fb035b2daf0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fb035b69af0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fb035b6c1f0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 272, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7fb035b04dc0>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7fb035adceb0>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fb035b4f4f0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/_server.py", line 154, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7fb035b69dc0>
               │       └ user_id: 1
               │         name: "\346\256\265\350\266\205123"
               │         mobile: "18612917508"
               │         address: "\345\215\216\344\270\2551code"
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7fb035b6c280>

> File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 269, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ user_id: 1
           │    │                   │             name: "\346\256\265\350\266\205123"
           │    │                   │             mobile: "18612917508"
           │    │                   │             address: "\345\215\216\344\270\2551code"
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fb035b4f4f0>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 150, in CreateOrder
    ret = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7fb034f4f8b0>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7fb035b23b50>
          │ │                           └ <rocketmq.client.Message object at 0x7fb035b69eb0>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7fb03364fa60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7fb035b69e20>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 335, in send_message_in_transaction
    ffi_check(
    └ <function ffi_check at 0x7fb0336379d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/exceptions.py", line 44, in ffi_check
    raise exc_cls(msg)
          │       └ 'msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> li...
          └ <class 'rocketmq.exceptions.RocketMQException'>

rocketmq.exceptions.RocketMQException: msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> line:418,error:-1,in file </Users/shannon/work/OpenSource/Apache/rocketmq-client-cpp/src/producer/TransactionMQProducerImpl.cpp line:53
2022-08-15 15:16:18.849 | ERROR    | grpc_opentracing.grpcext._interceptor:handler:269 - An error has been caught in function 'handler', process 'MainProcess' (92033), thread 'ThreadPoolExecutor-0_0' (123145633210368):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fb0330e9c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145633210368)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fb0330e9940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145633210368)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145633210368)>
    │    │        │    └ (<weakref at 0x7fb035b48d10; to 'ThreadPoolExecutor' at 0x7fb035adcf10>, <_queue.SimpleQueue object at 0x7fb035af6220>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145633210368)>
    │    └ <function _worker at 0x7fb035b005e0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145633210368)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fb035b00430>
    └ <concurrent.futures.thread._WorkItem object at 0x7fb035b69520>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fb035b69520>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fb035b57040>, <grpc._server._RPCState object at 0x7fb035b4ff10>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fb035b69520>
             │    └ <function _unary_response_in_pool at 0x7fb035b2dee0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fb035b69520>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fb035b6c1f0>
                        │              │          └ <grpc._server._RPCState object at 0x7fb035b4ff10>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fb035b57040>
                        └ <function _call_behavior at 0x7fb035b2daf0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fb035b69af0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fb035b6c1f0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 272, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7fb035b04dc0>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7fb035adceb0>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fb035b4f4f0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/_server.py", line 154, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7fb035b69dc0>
               │       └ user_id: 1
               │         name: "\346\256\265\350\266\205123"
               │         mobile: "18612917508"
               │         address: "\345\215\216\344\270\2551code"
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7fb035b6c280>

> File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 269, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ user_id: 1
           │    │                   │             name: "\346\256\265\350\266\205123"
           │    │                   │             mobile: "18612917508"
           │    │                   │             address: "\345\215\216\344\270\2551code"
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fb035b4f4f0>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 150, in CreateOrder
    ret = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7fb034f4f8b0>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7fb035b23b50>
          │ │                           └ <rocketmq.client.Message object at 0x7fb035b69eb0>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7fb03364fa60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7fb035b69e20>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 335, in send_message_in_transaction
    ffi_check(
    └ <function ffi_check at 0x7fb0336379d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/exceptions.py", line 44, in ffi_check
    raise exc_cls(msg)
          │       └ 'msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> li...
          └ <class 'rocketmq.exceptions.RocketMQException'>

rocketmq.exceptions.RocketMQException: msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> line:418,error:-1,in file </Users/shannon/work/OpenSource/Apache/rocketmq-client-cpp/src/producer/TransactionMQProducerImpl.cpp line:53
2022-08-15 15:16:18.849 | ERROR    | grpc_opentracing.grpcext._interceptor:handler:269 - An error has been caught in function 'handler', process 'MainProcess' (92033), thread 'ThreadPoolExecutor-0_0' (123145633210368):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fb0330e9c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145633210368)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fb0330e9940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145633210368)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145633210368)>
    │    │        │    └ (<weakref at 0x7fb035b48d10; to 'ThreadPoolExecutor' at 0x7fb035adcf10>, <_queue.SimpleQueue object at 0x7fb035af6220>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145633210368)>
    │    └ <function _worker at 0x7fb035b005e0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145633210368)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fb035b00430>
    └ <concurrent.futures.thread._WorkItem object at 0x7fb035b69520>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fb035b69520>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fb035b57040>, <grpc._server._RPCState object at 0x7fb035b4ff10>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fb035b69520>
             │    └ <function _unary_response_in_pool at 0x7fb035b2dee0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fb035b69520>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fb035b6c1f0>
                        │              │          └ <grpc._server._RPCState object at 0x7fb035b4ff10>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fb035b57040>
                        └ <function _call_behavior at 0x7fb035b2daf0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fb035b69af0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fb035b6c1f0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 272, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7fb035b04dc0>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7fb035adceb0>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fb035b4f4f0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/_server.py", line 154, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7fb035b69dc0>
               │       └ user_id: 1
               │         name: "\346\256\265\350\266\205123"
               │         mobile: "18612917508"
               │         address: "\345\215\216\344\270\2551code"
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7fb035b6c280>

> File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 269, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ user_id: 1
           │    │                   │             name: "\346\256\265\350\266\205123"
           │    │                   │             mobile: "18612917508"
           │    │                   │             address: "\345\215\216\344\270\2551code"
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fb035b4f4f0>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 150, in CreateOrder
    ret = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7fb034f4f8b0>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7fb035b23b50>
          │ │                           └ <rocketmq.client.Message object at 0x7fb035b69eb0>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7fb03364fa60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7fb035b69e20>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 335, in send_message_in_transaction
    ffi_check(
    └ <function ffi_check at 0x7fb0336379d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/exceptions.py", line 44, in ffi_check
    raise exc_cls(msg)
          │       └ 'msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> li...
          └ <class 'rocketmq.exceptions.RocketMQException'>

rocketmq.exceptions.RocketMQException: msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> line:418,error:-1,in file </Users/shannon/work/OpenSource/Apache/rocketmq-client-cpp/src/producer/TransactionMQProducerImpl.cpp line:53
2022-08-15 15:22:45.762 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:22:45.762 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:22:45.762 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:22:49.986 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:22:49.986 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:22:49.986 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:22:57.038 | ERROR    | grpc_opentracing.grpcext._interceptor:handler:269 - An error has been caught in function 'handler', process 'MainProcess' (92522), thread 'ThreadPoolExecutor-0_0' (123145427496960):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f8dc9ecec10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145427496960)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f8dc9ece940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145427496960)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145427496960)>
    │    │        │    └ (<weakref at 0x7f8dcca46d10; to 'ThreadPoolExecutor' at 0x7f8dcc9e3e80>, <_queue.SimpleQueue object at 0x7f8dcc9f5b80>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145427496960)>
    │    └ <function _worker at 0x7f8dcc9fd9d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145427496960)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f8dcc9fd8b0>
    └ <concurrent.futures.thread._WorkItem object at 0x7f8dcca4e9d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f8dcca4e9d0>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f8dcca468b0>, <grpc._server._RPCState object at 0x7f8dcca3f7c0>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f8dcca4e9d0>
             │    └ <function _unary_response_in_pool at 0x7f8dcca2aee0>
             └ <concurrent.futures.thread._WorkItem object at 0x7f8dcca4e9d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7f8dcca44e50>
                        │              │          └ <grpc._server._RPCState object at 0x7f8dcca3f7c0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f8dcca468b0>
                        └ <function _call_behavior at 0x7f8dcca2aaf0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f8dcca4ea60>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7f8dcca44e50>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 272, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7f8dcca01dc0>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7f8dcc9e3e20>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7f8dcc9e3670>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/_server.py", line 154, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7f8dcca4ecd0>
               │       └ user_id: 1
               │         name: "\346\256\265\350\266\205123"
               │         mobile: "18612917508"
               │         address: "\345\215\216\344\270\2551code"
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7f8dcca44ee0>

> File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 269, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ user_id: 1
           │    │                   │             name: "\346\256\265\350\266\205123"
           │    │                   │             mobile: "18612917508"
           │    │                   │             address: "\345\215\216\344\270\2551code"
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7f8dcc9e3670>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 150, in CreateOrder
    ret = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7f8dcc5498b0>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7f8dcca1f9a0>
          │ │                           └ <rocketmq.client.Message object at 0x7f8dcca4edc0>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7f8dcb518a60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7f8dcca4ed30>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 335, in send_message_in_transaction
    ffi_check(
    └ <function ffi_check at 0x7f8dcb5019d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/exceptions.py", line 44, in ffi_check
    raise exc_cls(msg)
          │       └ 'msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> li...
          └ <class 'rocketmq.exceptions.RocketMQException'>

rocketmq.exceptions.RocketMQException: msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> line:418,error:-1,in file </Users/shannon/work/OpenSource/Apache/rocketmq-client-cpp/src/producer/TransactionMQProducerImpl.cpp line:53
2022-08-15 15:22:57.038 | ERROR    | grpc_opentracing.grpcext._interceptor:handler:269 - An error has been caught in function 'handler', process 'MainProcess' (92522), thread 'ThreadPoolExecutor-0_0' (123145427496960):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f8dc9ecec10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145427496960)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f8dc9ece940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145427496960)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145427496960)>
    │    │        │    └ (<weakref at 0x7f8dcca46d10; to 'ThreadPoolExecutor' at 0x7f8dcc9e3e80>, <_queue.SimpleQueue object at 0x7f8dcc9f5b80>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145427496960)>
    │    └ <function _worker at 0x7f8dcc9fd9d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145427496960)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f8dcc9fd8b0>
    └ <concurrent.futures.thread._WorkItem object at 0x7f8dcca4e9d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f8dcca4e9d0>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f8dcca468b0>, <grpc._server._RPCState object at 0x7f8dcca3f7c0>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f8dcca4e9d0>
             │    └ <function _unary_response_in_pool at 0x7f8dcca2aee0>
             └ <concurrent.futures.thread._WorkItem object at 0x7f8dcca4e9d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7f8dcca44e50>
                        │              │          └ <grpc._server._RPCState object at 0x7f8dcca3f7c0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f8dcca468b0>
                        └ <function _call_behavior at 0x7f8dcca2aaf0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f8dcca4ea60>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7f8dcca44e50>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 272, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7f8dcca01dc0>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7f8dcc9e3e20>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7f8dcc9e3670>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/_server.py", line 154, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7f8dcca4ecd0>
               │       └ user_id: 1
               │         name: "\346\256\265\350\266\205123"
               │         mobile: "18612917508"
               │         address: "\345\215\216\344\270\2551code"
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7f8dcca44ee0>

> File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 269, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ user_id: 1
           │    │                   │             name: "\346\256\265\350\266\205123"
           │    │                   │             mobile: "18612917508"
           │    │                   │             address: "\345\215\216\344\270\2551code"
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7f8dcc9e3670>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 150, in CreateOrder
    ret = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7f8dcc5498b0>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7f8dcca1f9a0>
          │ │                           └ <rocketmq.client.Message object at 0x7f8dcca4edc0>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7f8dcb518a60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7f8dcca4ed30>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 335, in send_message_in_transaction
    ffi_check(
    └ <function ffi_check at 0x7f8dcb5019d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/exceptions.py", line 44, in ffi_check
    raise exc_cls(msg)
          │       └ 'msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> li...
          └ <class 'rocketmq.exceptions.RocketMQException'>

rocketmq.exceptions.RocketMQException: msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> line:418,error:-1,in file </Users/shannon/work/OpenSource/Apache/rocketmq-client-cpp/src/producer/TransactionMQProducerImpl.cpp line:53
2022-08-15 15:22:57.038 | ERROR    | grpc_opentracing.grpcext._interceptor:handler:269 - An error has been caught in function 'handler', process 'MainProcess' (92522), thread 'ThreadPoolExecutor-0_0' (123145427496960):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f8dc9ecec10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145427496960)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f8dc9ece940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145427496960)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145427496960)>
    │    │        │    └ (<weakref at 0x7f8dcca46d10; to 'ThreadPoolExecutor' at 0x7f8dcc9e3e80>, <_queue.SimpleQueue object at 0x7f8dcc9f5b80>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145427496960)>
    │    └ <function _worker at 0x7f8dcc9fd9d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145427496960)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f8dcc9fd8b0>
    └ <concurrent.futures.thread._WorkItem object at 0x7f8dcca4e9d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f8dcca4e9d0>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f8dcca468b0>, <grpc._server._RPCState object at 0x7f8dcca3f7c0>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f8dcca4e9d0>
             │    └ <function _unary_response_in_pool at 0x7f8dcca2aee0>
             └ <concurrent.futures.thread._WorkItem object at 0x7f8dcca4e9d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7f8dcca44e50>
                        │              │          └ <grpc._server._RPCState object at 0x7f8dcca3f7c0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f8dcca468b0>
                        └ <function _call_behavior at 0x7f8dcca2aaf0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f8dcca4ea60>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7f8dcca44e50>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 272, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7f8dcca01dc0>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7f8dcc9e3e20>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7f8dcc9e3670>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/_server.py", line 154, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7f8dcca4ecd0>
               │       └ user_id: 1
               │         name: "\346\256\265\350\266\205123"
               │         mobile: "18612917508"
               │         address: "\345\215\216\344\270\2551code"
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7f8dcca44ee0>

> File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 269, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ user_id: 1
           │    │                   │             name: "\346\256\265\350\266\205123"
           │    │                   │             mobile: "18612917508"
           │    │                   │             address: "\345\215\216\344\270\2551code"
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7f8dcc9e3670>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 150, in CreateOrder
    ret = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7f8dcc5498b0>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7f8dcca1f9a0>
          │ │                           └ <rocketmq.client.Message object at 0x7f8dcca4edc0>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7f8dcb518a60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7f8dcca4ed30>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 335, in send_message_in_transaction
    ffi_check(
    └ <function ffi_check at 0x7f8dcb5019d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/exceptions.py", line 44, in ffi_check
    raise exc_cls(msg)
          │       └ 'msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> li...
          └ <class 'rocketmq.exceptions.RocketMQException'>

rocketmq.exceptions.RocketMQException: msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> line:418,error:-1,in file </Users/shannon/work/OpenSource/Apache/rocketmq-client-cpp/src/producer/TransactionMQProducerImpl.cpp line:53
2022-08-15 15:25:09.304 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:25:09.304 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:25:09.304 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:25:12.212 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:25:12.212 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:25:12.212 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:25:16.556 | ERROR    | grpc_opentracing.grpcext._interceptor:handler:269 - An error has been caught in function 'handler', process 'MainProcess' (92664), thread 'ThreadPoolExecutor-0_0' (123145568952320):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe21aecec10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145568952320)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe21aece940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145568952320)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145568952320)>
    │    │        │    └ (<weakref at 0x7fe21f347d10; to 'ThreadPoolExecutor' at 0x7fe21f19cf10>, <_queue.SimpleQueue object at 0x7fe21f1a7a40>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145568952320)>
    │    └ <function _worker at 0x7fe21f1c05e0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145568952320)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fe21f1c0430>
    └ <concurrent.futures.thread._WorkItem object at 0x7fe21f34ea60>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fe21f34ea60>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fe21f3478b0>, <grpc._server._RPCState object at 0x7fe21f19c6d0>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fe21f34ea60>
             │    └ <function _unary_response_in_pool at 0x7fe21f32bee0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fe21f34ea60>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fe21f346e50>
                        │              │          └ <grpc._server._RPCState object at 0x7fe21f19c6d0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fe21f3478b0>
                        └ <function _call_behavior at 0x7fe21f32baf0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fe21f34eaf0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fe21f346e50>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 272, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7fe21f303dc0>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7fe21f19ceb0>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fe21f3437f0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/_server.py", line 154, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7fe21f34ed30>
               │       └ user_id: 1
               │         name: "\346\256\265\350\266\205123"
               │         mobile: "18612917508"
               │         address: "\345\215\216\344\270\2551code"
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7fe21f346ee0>

> File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 269, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ user_id: 1
           │    │                   │             name: "\346\256\265\350\266\205123"
           │    │                   │             mobile: "18612917508"
           │    │                   │             address: "\345\215\216\344\270\2551code"
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fe21f3437f0>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 150, in CreateOrder
    ret = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7fe21dd328b0>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7fe21f322b50>
          │ │                           └ <rocketmq.client.Message object at 0x7fe21f34ee20>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7fe21cc0fa60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7fe21f34ed90>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 335, in send_message_in_transaction
    ffi_check(
    └ <function ffi_check at 0x7fe21cbf89d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/exceptions.py", line 44, in ffi_check
    raise exc_cls(msg)
          │       └ 'msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> li...
          └ <class 'rocketmq.exceptions.RocketMQException'>

rocketmq.exceptions.RocketMQException: msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> line:418,error:-1,in file </Users/shannon/work/OpenSource/Apache/rocketmq-client-cpp/src/producer/TransactionMQProducerImpl.cpp line:53
2022-08-15 15:25:16.556 | ERROR    | grpc_opentracing.grpcext._interceptor:handler:269 - An error has been caught in function 'handler', process 'MainProcess' (92664), thread 'ThreadPoolExecutor-0_0' (123145568952320):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe21aecec10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145568952320)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe21aece940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145568952320)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145568952320)>
    │    │        │    └ (<weakref at 0x7fe21f347d10; to 'ThreadPoolExecutor' at 0x7fe21f19cf10>, <_queue.SimpleQueue object at 0x7fe21f1a7a40>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145568952320)>
    │    └ <function _worker at 0x7fe21f1c05e0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145568952320)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fe21f1c0430>
    └ <concurrent.futures.thread._WorkItem object at 0x7fe21f34ea60>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fe21f34ea60>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fe21f3478b0>, <grpc._server._RPCState object at 0x7fe21f19c6d0>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fe21f34ea60>
             │    └ <function _unary_response_in_pool at 0x7fe21f32bee0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fe21f34ea60>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fe21f346e50>
                        │              │          └ <grpc._server._RPCState object at 0x7fe21f19c6d0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fe21f3478b0>
                        └ <function _call_behavior at 0x7fe21f32baf0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fe21f34eaf0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fe21f346e50>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 272, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7fe21f303dc0>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7fe21f19ceb0>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fe21f3437f0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/_server.py", line 154, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7fe21f34ed30>
               │       └ user_id: 1
               │         name: "\346\256\265\350\266\205123"
               │         mobile: "18612917508"
               │         address: "\345\215\216\344\270\2551code"
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7fe21f346ee0>

> File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 269, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ user_id: 1
           │    │                   │             name: "\346\256\265\350\266\205123"
           │    │                   │             mobile: "18612917508"
           │    │                   │             address: "\345\215\216\344\270\2551code"
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fe21f3437f0>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 150, in CreateOrder
    ret = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7fe21dd328b0>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7fe21f322b50>
          │ │                           └ <rocketmq.client.Message object at 0x7fe21f34ee20>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7fe21cc0fa60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7fe21f34ed90>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 335, in send_message_in_transaction
    ffi_check(
    └ <function ffi_check at 0x7fe21cbf89d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/exceptions.py", line 44, in ffi_check
    raise exc_cls(msg)
          │       └ 'msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> li...
          └ <class 'rocketmq.exceptions.RocketMQException'>

rocketmq.exceptions.RocketMQException: msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> line:418,error:-1,in file </Users/shannon/work/OpenSource/Apache/rocketmq-client-cpp/src/producer/TransactionMQProducerImpl.cpp line:53
2022-08-15 15:25:16.556 | ERROR    | grpc_opentracing.grpcext._interceptor:handler:269 - An error has been caught in function 'handler', process 'MainProcess' (92664), thread 'ThreadPoolExecutor-0_0' (123145568952320):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe21aecec10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145568952320)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe21aece940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145568952320)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145568952320)>
    │    │        │    └ (<weakref at 0x7fe21f347d10; to 'ThreadPoolExecutor' at 0x7fe21f19cf10>, <_queue.SimpleQueue object at 0x7fe21f1a7a40>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145568952320)>
    │    └ <function _worker at 0x7fe21f1c05e0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145568952320)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fe21f1c0430>
    └ <concurrent.futures.thread._WorkItem object at 0x7fe21f34ea60>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fe21f34ea60>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fe21f3478b0>, <grpc._server._RPCState object at 0x7fe21f19c6d0>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fe21f34ea60>
             │    └ <function _unary_response_in_pool at 0x7fe21f32bee0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fe21f34ea60>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fe21f346e50>
                        │              │          └ <grpc._server._RPCState object at 0x7fe21f19c6d0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fe21f3478b0>
                        └ <function _call_behavior at 0x7fe21f32baf0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fe21f34eaf0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fe21f346e50>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 272, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7fe21f303dc0>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7fe21f19ceb0>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fe21f3437f0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/_server.py", line 154, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7fe21f34ed30>
               │       └ user_id: 1
               │         name: "\346\256\265\350\266\205123"
               │         mobile: "18612917508"
               │         address: "\345\215\216\344\270\2551code"
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7fe21f346ee0>

> File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 269, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ user_id: 1
           │    │                   │             name: "\346\256\265\350\266\205123"
           │    │                   │             mobile: "18612917508"
           │    │                   │             address: "\345\215\216\344\270\2551code"
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fe21f3437f0>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 150, in CreateOrder
    ret = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7fe21dd328b0>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7fe21f322b50>
          │ │                           └ <rocketmq.client.Message object at 0x7fe21f34ee20>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7fe21cc0fa60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7fe21f34ed90>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 335, in send_message_in_transaction
    ffi_check(
    └ <function ffi_check at 0x7fe21cbf89d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/exceptions.py", line 44, in ffi_check
    raise exc_cls(msg)
          │       └ 'msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> li...
          └ <class 'rocketmq.exceptions.RocketMQException'>

rocketmq.exceptions.RocketMQException: msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> line:418,error:-1,in file </Users/shannon/work/OpenSource/Apache/rocketmq-client-cpp/src/producer/TransactionMQProducerImpl.cpp line:53
2022-08-15 15:25:19.208 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:25:19.208 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:25:19.208 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:28:07.567 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:28:07.567 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:28:07.567 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:28:11.234 | ERROR    | rocketmq.client:_on_local_execute:317 - An error has been caught in function '_on_local_execute', process 'MainProcess' (92842), thread 'ThreadPoolExecutor-0_0' (123145397387264):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe83efe9c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145397387264)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe83efe9940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145397387264)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145397387264)>
    │    │        │    └ (<weakref at 0x7fe843b48c70; to 'ThreadPoolExecutor' at 0x7fe843adceb0>, <_queue.SimpleQueue object at 0x7fe843ae7ea0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145397387264)>
    │    └ <function _worker at 0x7fe843b005e0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145397387264)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fe843b00430>
    └ <concurrent.futures.thread._WorkItem object at 0x7fe843b45580>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fe843b45580>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fe843b48540>, <grpc._server._RPCState object at 0x7fe843b45820>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fe843b45580>
             │    └ <function _unary_response_in_pool at 0x7fe843b2dca0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fe843b45580>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fe843b479d0>
                        │              │          └ <grpc._server._RPCState object at 0x7fe843b45820>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fe843b48540>
                        └ <function _call_behavior at 0x7fe843b2d8b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fe843b51340>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fe843b479d0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 272, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7fe843b04dc0>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7fe843adce50>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fe843b457c0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/_server.py", line 154, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7fe843b51550>
               │       └ user_id: 1
               │         name: "\346\256\265\350\266\205123"
               │         mobile: "18612917508"
               │         address: "\345\215\216\344\270\2551code"
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7fe843b47c10>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 269, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ user_id: 1
           │    │                   │             name: "\346\256\265\350\266\205123"
           │    │                   │             mobile: "18612917508"
           │    │                   │             address: "\345\215\216\344\270\2551code"
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fe843b457c0>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 151, in CreateOrder
    ret = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7fe8427548b0>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7fe843b23970>
          │ │                           └ <rocketmq.client.Message object at 0x7fe843b51760>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7fe84064fa60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7fe843b516a0>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 336, in send_message_in_transaction
    dll.SendMessageTransaction(self._handle,
    │   │                      │    └ 105553153954368
    │   │                      └ <rocketmq.client.TransactionMQProducer object at 0x7fe843b516a0>
    │   └ <_FuncPtr object at 0x7fe84063de80>
    └ <CDLL '/usr/local/lib/librocketmq.dylib', handle 2174dbce0 at 0x7fe8405e0400>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 317, in _on_local_execute
    local_result = local_execute(py_message, usr_args)
                   │             │           └ None
                   │             └ <ReceivedMessage topic='transTopic' id='serializeTypeCurrentRPC":"JSON","version":373}' body=b'{"order_sn": "2022081515281115...
                   └ <bound method OrderServicer.local_execute of <handler.order.OrderServicer object at 0x7fe843b23970>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 185, in local_execute
    print(span.context.get_active_span())
          │    └ <property object at 0x7fe842509360>
          └ defeb8cdb285e292:62782006465f43ee:8dc0b1627f6061e6:1 order-dao.local_execute_shopcart

AttributeError: 'SpanContext' object has no attribute 'get_active_span'
2022-08-15 15:28:11.234 | ERROR    | rocketmq.client:_on_local_execute:317 - An error has been caught in function '_on_local_execute', process 'MainProcess' (92842), thread 'ThreadPoolExecutor-0_0' (123145397387264):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe83efe9c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145397387264)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe83efe9940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145397387264)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145397387264)>
    │    │        │    └ (<weakref at 0x7fe843b48c70; to 'ThreadPoolExecutor' at 0x7fe843adceb0>, <_queue.SimpleQueue object at 0x7fe843ae7ea0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145397387264)>
    │    └ <function _worker at 0x7fe843b005e0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145397387264)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fe843b00430>
    └ <concurrent.futures.thread._WorkItem object at 0x7fe843b45580>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fe843b45580>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fe843b48540>, <grpc._server._RPCState object at 0x7fe843b45820>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fe843b45580>
             │    └ <function _unary_response_in_pool at 0x7fe843b2dca0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fe843b45580>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fe843b479d0>
                        │              │          └ <grpc._server._RPCState object at 0x7fe843b45820>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fe843b48540>
                        └ <function _call_behavior at 0x7fe843b2d8b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fe843b51340>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fe843b479d0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 272, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7fe843b04dc0>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7fe843adce50>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fe843b457c0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/_server.py", line 154, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7fe843b51550>
               │       └ user_id: 1
               │         name: "\346\256\265\350\266\205123"
               │         mobile: "18612917508"
               │         address: "\345\215\216\344\270\2551code"
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7fe843b47c10>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 269, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ user_id: 1
           │    │                   │             name: "\346\256\265\350\266\205123"
           │    │                   │             mobile: "18612917508"
           │    │                   │             address: "\345\215\216\344\270\2551code"
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fe843b457c0>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 151, in CreateOrder
    ret = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7fe8427548b0>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7fe843b23970>
          │ │                           └ <rocketmq.client.Message object at 0x7fe843b51760>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7fe84064fa60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7fe843b516a0>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 336, in send_message_in_transaction
    dll.SendMessageTransaction(self._handle,
    │   │                      │    └ 105553153954368
    │   │                      └ <rocketmq.client.TransactionMQProducer object at 0x7fe843b516a0>
    │   └ <_FuncPtr object at 0x7fe84063de80>
    └ <CDLL '/usr/local/lib/librocketmq.dylib', handle 2174dbce0 at 0x7fe8405e0400>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 317, in _on_local_execute
    local_result = local_execute(py_message, usr_args)
                   │             │           └ None
                   │             └ <ReceivedMessage topic='transTopic' id='serializeTypeCurrentRPC":"JSON","version":373}' body=b'{"order_sn": "2022081515281115...
                   └ <bound method OrderServicer.local_execute of <handler.order.OrderServicer object at 0x7fe843b23970>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 185, in local_execute
    print(span.context.get_active_span())
          │    └ <property object at 0x7fe842509360>
          └ defeb8cdb285e292:62782006465f43ee:8dc0b1627f6061e6:1 order-dao.local_execute_shopcart

AttributeError: 'SpanContext' object has no attribute 'get_active_span'
2022-08-15 15:28:11.234 | ERROR    | rocketmq.client:_on_local_execute:317 - An error has been caught in function '_on_local_execute', process 'MainProcess' (92842), thread 'ThreadPoolExecutor-0_0' (123145397387264):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe83efe9c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145397387264)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe83efe9940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145397387264)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145397387264)>
    │    │        │    └ (<weakref at 0x7fe843b48c70; to 'ThreadPoolExecutor' at 0x7fe843adceb0>, <_queue.SimpleQueue object at 0x7fe843ae7ea0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145397387264)>
    │    └ <function _worker at 0x7fe843b005e0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145397387264)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fe843b00430>
    └ <concurrent.futures.thread._WorkItem object at 0x7fe843b45580>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fe843b45580>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fe843b48540>, <grpc._server._RPCState object at 0x7fe843b45820>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fe843b45580>
             │    └ <function _unary_response_in_pool at 0x7fe843b2dca0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fe843b45580>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fe843b479d0>
                        │              │          └ <grpc._server._RPCState object at 0x7fe843b45820>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fe843b48540>
                        └ <function _call_behavior at 0x7fe843b2d8b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fe843b51340>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fe843b479d0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 272, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7fe843b04dc0>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7fe843adce50>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fe843b457c0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/_server.py", line 154, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7fe843b51550>
               │       └ user_id: 1
               │         name: "\346\256\265\350\266\205123"
               │         mobile: "18612917508"
               │         address: "\345\215\216\344\270\2551code"
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7fe843b47c10>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 269, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ user_id: 1
           │    │                   │             name: "\346\256\265\350\266\205123"
           │    │                   │             mobile: "18612917508"
           │    │                   │             address: "\345\215\216\344\270\2551code"
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fe843b457c0>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 151, in CreateOrder
    ret = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7fe8427548b0>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7fe843b23970>
          │ │                           └ <rocketmq.client.Message object at 0x7fe843b51760>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7fe84064fa60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7fe843b516a0>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 336, in send_message_in_transaction
    dll.SendMessageTransaction(self._handle,
    │   │                      │    └ 105553153954368
    │   │                      └ <rocketmq.client.TransactionMQProducer object at 0x7fe843b516a0>
    │   └ <_FuncPtr object at 0x7fe84063de80>
    └ <CDLL '/usr/local/lib/librocketmq.dylib', handle 2174dbce0 at 0x7fe8405e0400>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 317, in _on_local_execute
    local_result = local_execute(py_message, usr_args)
                   │             │           └ None
                   │             └ <ReceivedMessage topic='transTopic' id='serializeTypeCurrentRPC":"JSON","version":373}' body=b'{"order_sn": "2022081515281115...
                   └ <bound method OrderServicer.local_execute of <handler.order.OrderServicer object at 0x7fe843b23970>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 185, in local_execute
    print(span.context.get_active_span())
          │    └ <property object at 0x7fe842509360>
          └ defeb8cdb285e292:62782006465f43ee:8dc0b1627f6061e6:1 order-dao.local_execute_shopcart

AttributeError: 'SpanContext' object has no attribute 'get_active_span'
2022-08-15 15:34:16.372 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:34:16.372 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:34:16.372 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:34:18.455 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:34:18.455 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:34:18.455 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:34:39.228 | ERROR    | grpc_opentracing.grpcext._interceptor:handler:269 - An error has been caught in function 'handler', process 'MainProcess' (93221), thread 'ThreadPoolExecutor-0_0' (123145423056896):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f913e6cec10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145423056896)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f913e6ce940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145423056896)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145423056896)>
    │    │        │    └ (<weakref at 0x7f9143309db0; to 'ThreadPoolExecutor' at 0x7f914329df10>, <_queue.SimpleQueue object at 0x7f91432b72c0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145423056896)>
    │    └ <function _worker at 0x7f91432c15e0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145423056896)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f91432c1430>
    └ <concurrent.futures.thread._WorkItem object at 0x7f9143310b50>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f9143310b50>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f91433099f0>, <grpc._server._RPCState object at 0x7f914329d6a0>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f9143310b50>
             │    └ <function _unary_response_in_pool at 0x7f91432edee0>
             └ <concurrent.futures.thread._WorkItem object at 0x7f9143310b50>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7f9143308a60>
                        │              │          └ <grpc._server._RPCState object at 0x7f914329d6a0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f91433099f0>
                        └ <function _call_behavior at 0x7f91432edaf0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f9143310610>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7f9143308a60>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 272, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7f91432c5dc0>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7f914329deb0>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7f91433107f0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/_server.py", line 154, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7f9143310e80>
               │       └ user_id: 1
               │         name: "\346\256\265\350\266\205123"
               │         mobile: "18612917508"
               │         address: "\345\215\216\344\270\2551code"
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7f9143308f70>

> File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 269, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ user_id: 1
           │    │                   │             name: "\346\256\265\350\266\205123"
           │    │                   │             mobile: "18612917508"
           │    │                   │             address: "\345\215\216\344\270\2551code"
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7f91433107f0>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 150, in CreateOrder
    ret = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7f9142f498b0>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7f91432e4b50>
          │ │                           └ <rocketmq.client.Message object at 0x7f9143310f70>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7f9140f4fa60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7f9143310ee0>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 335, in send_message_in_transaction
    ffi_check(
    └ <function ffi_check at 0x7f9140f389d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/exceptions.py", line 44, in ffi_check
    raise exc_cls(msg)
          │       └ 'msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> li...
          └ <class 'rocketmq.exceptions.RocketMQException'>

rocketmq.exceptions.RocketMQException: msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> line:418,error:-1,in file </Users/shannon/work/OpenSource/Apache/rocketmq-client-cpp/src/producer/TransactionMQProducerImpl.cpp line:53
2022-08-15 15:34:39.228 | ERROR    | grpc_opentracing.grpcext._interceptor:handler:269 - An error has been caught in function 'handler', process 'MainProcess' (93221), thread 'ThreadPoolExecutor-0_0' (123145423056896):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f913e6cec10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145423056896)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f913e6ce940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145423056896)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145423056896)>
    │    │        │    └ (<weakref at 0x7f9143309db0; to 'ThreadPoolExecutor' at 0x7f914329df10>, <_queue.SimpleQueue object at 0x7f91432b72c0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145423056896)>
    │    └ <function _worker at 0x7f91432c15e0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145423056896)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f91432c1430>
    └ <concurrent.futures.thread._WorkItem object at 0x7f9143310b50>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f9143310b50>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f91433099f0>, <grpc._server._RPCState object at 0x7f914329d6a0>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f9143310b50>
             │    └ <function _unary_response_in_pool at 0x7f91432edee0>
             └ <concurrent.futures.thread._WorkItem object at 0x7f9143310b50>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7f9143308a60>
                        │              │          └ <grpc._server._RPCState object at 0x7f914329d6a0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f91433099f0>
                        └ <function _call_behavior at 0x7f91432edaf0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f9143310610>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7f9143308a60>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 272, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7f91432c5dc0>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7f914329deb0>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7f91433107f0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/_server.py", line 154, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7f9143310e80>
               │       └ user_id: 1
               │         name: "\346\256\265\350\266\205123"
               │         mobile: "18612917508"
               │         address: "\345\215\216\344\270\2551code"
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7f9143308f70>

> File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 269, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ user_id: 1
           │    │                   │             name: "\346\256\265\350\266\205123"
           │    │                   │             mobile: "18612917508"
           │    │                   │             address: "\345\215\216\344\270\2551code"
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7f91433107f0>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 150, in CreateOrder
    ret = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7f9142f498b0>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7f91432e4b50>
          │ │                           └ <rocketmq.client.Message object at 0x7f9143310f70>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7f9140f4fa60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7f9143310ee0>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 335, in send_message_in_transaction
    ffi_check(
    └ <function ffi_check at 0x7f9140f389d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/exceptions.py", line 44, in ffi_check
    raise exc_cls(msg)
          │       └ 'msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> li...
          └ <class 'rocketmq.exceptions.RocketMQException'>

rocketmq.exceptions.RocketMQException: msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> line:418,error:-1,in file </Users/shannon/work/OpenSource/Apache/rocketmq-client-cpp/src/producer/TransactionMQProducerImpl.cpp line:53
2022-08-15 15:34:39.228 | ERROR    | grpc_opentracing.grpcext._interceptor:handler:269 - An error has been caught in function 'handler', process 'MainProcess' (93221), thread 'ThreadPoolExecutor-0_0' (123145423056896):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f913e6cec10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145423056896)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f913e6ce940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145423056896)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145423056896)>
    │    │        │    └ (<weakref at 0x7f9143309db0; to 'ThreadPoolExecutor' at 0x7f914329df10>, <_queue.SimpleQueue object at 0x7f91432b72c0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145423056896)>
    │    └ <function _worker at 0x7f91432c15e0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145423056896)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f91432c1430>
    └ <concurrent.futures.thread._WorkItem object at 0x7f9143310b50>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f9143310b50>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f91433099f0>, <grpc._server._RPCState object at 0x7f914329d6a0>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f9143310b50>
             │    └ <function _unary_response_in_pool at 0x7f91432edee0>
             └ <concurrent.futures.thread._WorkItem object at 0x7f9143310b50>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7f9143308a60>
                        │              │          └ <grpc._server._RPCState object at 0x7f914329d6a0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f91433099f0>
                        └ <function _call_behavior at 0x7f91432edaf0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f9143310610>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7f9143308a60>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 272, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7f91432c5dc0>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7f914329deb0>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7f91433107f0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/_server.py", line 154, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7f9143310e80>
               │       └ user_id: 1
               │         name: "\346\256\265\350\266\205123"
               │         mobile: "18612917508"
               │         address: "\345\215\216\344\270\2551code"
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7f9143308f70>

> File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 269, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ user_id: 1
           │    │                   │             name: "\346\256\265\350\266\205123"
           │    │                   │             mobile: "18612917508"
           │    │                   │             address: "\345\215\216\344\270\2551code"
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7f91433107f0>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 150, in CreateOrder
    ret = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7f9142f498b0>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7f91432e4b50>
          │ │                           └ <rocketmq.client.Message object at 0x7f9143310f70>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7f9140f4fa60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7f9143310ee0>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 335, in send_message_in_transaction
    ffi_check(
    └ <function ffi_check at 0x7f9140f389d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/exceptions.py", line 44, in ffi_check
    raise exc_cls(msg)
          │       └ 'msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> li...
          └ <class 'rocketmq.exceptions.RocketMQException'>

rocketmq.exceptions.RocketMQException: msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> line:418,error:-1,in file </Users/shannon/work/OpenSource/Apache/rocketmq-client-cpp/src/producer/TransactionMQProducerImpl.cpp line:53
2022-08-15 15:35:08.320 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:35:08.320 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:35:08.320 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:37:19.408 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:37:19.408 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:37:19.408 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:37:22.232 | ERROR    | handler.order:local_execute:207 - An error has been caught in function 'local_execute', process 'MainProcess' (93444), thread 'ThreadPoolExecutor-0_0' (123145384906752):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7ff10c9e9c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145384906752)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7ff10c9e9940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145384906752)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145384906752)>
    │    │        │    └ (<weakref at 0x7ff10eb07d60; to 'ThreadPoolExecutor' at 0x7ff10eaa6e50>, <_queue.SimpleQueue object at 0x7ff10eaa7f40>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145384906752)>
    │    └ <function _worker at 0x7ff10eaaa820>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145384906752)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7ff10eaaaca0>
    └ <concurrent.futures.thread._WorkItem object at 0x7ff10eb035b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7ff10eb035b0>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7ff10eb07630>, <grpc._server._RPCState object at 0x7ff10eb038b0>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7ff10eb035b0>
             │    └ <function _unary_response_in_pool at 0x7ff10eaecca0>
             └ <concurrent.futures.thread._WorkItem object at 0x7ff10eb035b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7ff10eb069d0>
                        │              │          └ <grpc._server._RPCState object at 0x7ff10eb038b0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7ff10eb07630>
                        └ <function _call_behavior at 0x7ff10eaec8b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7ff10eb122e0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7ff10eb069d0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 272, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7ff10eabf940>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7ff10eaa6df0>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7ff10eb037c0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/_server.py", line 154, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7ff10eb124f0>
               │       └ user_id: 1
               │         name: "\346\256\265\350\266\205123"
               │         mobile: "18612917508"
               │         address: "\345\215\216\344\270\2551code"
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7ff10eb06c10>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 269, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ user_id: 1
           │    │                   │             name: "\346\256\265\350\266\205123"
           │    │                   │             mobile: "18612917508"
           │    │                   │             address: "\345\215\216\344\270\2551code"
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7ff10eb037c0>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 150, in CreateOrder
    ret = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7ff10e7458b0>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7ff10eae1910>
          │ │                           └ <rocketmq.client.Message object at 0x7ff10eb12700>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7ff10cf4fa60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7ff10eb12640>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 336, in send_message_in_transaction
    dll.SendMessageTransaction(self._handle,
    │   │                      │    └ 105553160425632
    │   │                      └ <rocketmq.client.TransactionMQProducer object at 0x7ff10eb12640>
    │   └ <_FuncPtr object at 0x7ff10cf3de80>
    └ <CDLL '/usr/local/lib/librocketmq.dylib', handle 217825ce0 at 0x7ff10cee0400>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 317, in _on_local_execute
    local_result = local_execute(py_message, usr_args)
                   │             │           └ None
                   │             └ <ReceivedMessage topic='transTopic' id='' body=b'{"order_sn": "202208151537221205", "span_id": 18164471026988083044, "user_id...
                   └ <bound method OrderServicer.local_execute of <handler.order.OrderServicer object at 0x7ff10eae1910>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 207, in local_execute
    client = self._grpcClient(cfg["goods"]["name"], span)
             │    │           │                     └ 5de6ce15f34534a4:8a0f521925a68f6c:fc152a28d87fe764:1 order-dao.local_execute_goods
             │    │           └ {'name': 'order-dao', 'host': '192.168.8.222', 'port': 4347, 'consul': {'host': '192.168.8.222', 'port': 8500, 'tags': ['gpma...
             │    └ <function OrderServicer._grpcClient at 0x7ff10e745160>
             └ <handler.order.OrderServicer object at 0x7ff10eae1910>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 97, in _grpcClient
    span = ActiveSpanSource()
           └ <class 'common.grpc_opentracing.ActiveSpanSource'>

TypeError: Can't instantiate abstract class ActiveSpanSource with abstract method get_active_span
2022-08-15 15:37:22.232 | ERROR    | handler.order:local_execute:207 - An error has been caught in function 'local_execute', process 'MainProcess' (93444), thread 'ThreadPoolExecutor-0_0' (123145384906752):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7ff10c9e9c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145384906752)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7ff10c9e9940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145384906752)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145384906752)>
    │    │        │    └ (<weakref at 0x7ff10eb07d60; to 'ThreadPoolExecutor' at 0x7ff10eaa6e50>, <_queue.SimpleQueue object at 0x7ff10eaa7f40>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145384906752)>
    │    └ <function _worker at 0x7ff10eaaa820>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145384906752)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7ff10eaaaca0>
    └ <concurrent.futures.thread._WorkItem object at 0x7ff10eb035b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7ff10eb035b0>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7ff10eb07630>, <grpc._server._RPCState object at 0x7ff10eb038b0>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7ff10eb035b0>
             │    └ <function _unary_response_in_pool at 0x7ff10eaecca0>
             └ <concurrent.futures.thread._WorkItem object at 0x7ff10eb035b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7ff10eb069d0>
                        │              │          └ <grpc._server._RPCState object at 0x7ff10eb038b0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7ff10eb07630>
                        └ <function _call_behavior at 0x7ff10eaec8b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7ff10eb122e0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7ff10eb069d0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 272, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7ff10eabf940>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7ff10eaa6df0>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7ff10eb037c0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/_server.py", line 154, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7ff10eb124f0>
               │       └ user_id: 1
               │         name: "\346\256\265\350\266\205123"
               │         mobile: "18612917508"
               │         address: "\345\215\216\344\270\2551code"
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7ff10eb06c10>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 269, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ user_id: 1
           │    │                   │             name: "\346\256\265\350\266\205123"
           │    │                   │             mobile: "18612917508"
           │    │                   │             address: "\345\215\216\344\270\2551code"
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7ff10eb037c0>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 150, in CreateOrder
    ret = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7ff10e7458b0>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7ff10eae1910>
          │ │                           └ <rocketmq.client.Message object at 0x7ff10eb12700>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7ff10cf4fa60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7ff10eb12640>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 336, in send_message_in_transaction
    dll.SendMessageTransaction(self._handle,
    │   │                      │    └ 105553160425632
    │   │                      └ <rocketmq.client.TransactionMQProducer object at 0x7ff10eb12640>
    │   └ <_FuncPtr object at 0x7ff10cf3de80>
    └ <CDLL '/usr/local/lib/librocketmq.dylib', handle 217825ce0 at 0x7ff10cee0400>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 317, in _on_local_execute
    local_result = local_execute(py_message, usr_args)
                   │             │           └ None
                   │             └ <ReceivedMessage topic='transTopic' id='' body=b'{"order_sn": "202208151537221205", "span_id": 18164471026988083044, "user_id...
                   └ <bound method OrderServicer.local_execute of <handler.order.OrderServicer object at 0x7ff10eae1910>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 207, in local_execute
    client = self._grpcClient(cfg["goods"]["name"], span)
             │    │           │                     └ 5de6ce15f34534a4:8a0f521925a68f6c:fc152a28d87fe764:1 order-dao.local_execute_goods
             │    │           └ {'name': 'order-dao', 'host': '192.168.8.222', 'port': 4347, 'consul': {'host': '192.168.8.222', 'port': 8500, 'tags': ['gpma...
             │    └ <function OrderServicer._grpcClient at 0x7ff10e745160>
             └ <handler.order.OrderServicer object at 0x7ff10eae1910>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 97, in _grpcClient
    span = ActiveSpanSource()
           └ <class 'common.grpc_opentracing.ActiveSpanSource'>

TypeError: Can't instantiate abstract class ActiveSpanSource with abstract method get_active_span
2022-08-15 15:37:22.232 | ERROR    | handler.order:local_execute:207 - An error has been caught in function 'local_execute', process 'MainProcess' (93444), thread 'ThreadPoolExecutor-0_0' (123145384906752):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7ff10c9e9c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145384906752)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7ff10c9e9940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145384906752)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145384906752)>
    │    │        │    └ (<weakref at 0x7ff10eb07d60; to 'ThreadPoolExecutor' at 0x7ff10eaa6e50>, <_queue.SimpleQueue object at 0x7ff10eaa7f40>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145384906752)>
    │    └ <function _worker at 0x7ff10eaaa820>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145384906752)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7ff10eaaaca0>
    └ <concurrent.futures.thread._WorkItem object at 0x7ff10eb035b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7ff10eb035b0>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7ff10eb07630>, <grpc._server._RPCState object at 0x7ff10eb038b0>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7ff10eb035b0>
             │    └ <function _unary_response_in_pool at 0x7ff10eaecca0>
             └ <concurrent.futures.thread._WorkItem object at 0x7ff10eb035b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7ff10eb069d0>
                        │              │          └ <grpc._server._RPCState object at 0x7ff10eb038b0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7ff10eb07630>
                        └ <function _call_behavior at 0x7ff10eaec8b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7ff10eb122e0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7ff10eb069d0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 272, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7ff10eabf940>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7ff10eaa6df0>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7ff10eb037c0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/_server.py", line 154, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7ff10eb124f0>
               │       └ user_id: 1
               │         name: "\346\256\265\350\266\205123"
               │         mobile: "18612917508"
               │         address: "\345\215\216\344\270\2551code"
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7ff10eb06c10>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 269, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ user_id: 1
           │    │                   │             name: "\346\256\265\350\266\205123"
           │    │                   │             mobile: "18612917508"
           │    │                   │             address: "\345\215\216\344\270\2551code"
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7ff10eb037c0>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 150, in CreateOrder
    ret = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7ff10e7458b0>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7ff10eae1910>
          │ │                           └ <rocketmq.client.Message object at 0x7ff10eb12700>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7ff10cf4fa60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7ff10eb12640>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 336, in send_message_in_transaction
    dll.SendMessageTransaction(self._handle,
    │   │                      │    └ 105553160425632
    │   │                      └ <rocketmq.client.TransactionMQProducer object at 0x7ff10eb12640>
    │   └ <_FuncPtr object at 0x7ff10cf3de80>
    └ <CDLL '/usr/local/lib/librocketmq.dylib', handle 217825ce0 at 0x7ff10cee0400>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 317, in _on_local_execute
    local_result = local_execute(py_message, usr_args)
                   │             │           └ None
                   │             └ <ReceivedMessage topic='transTopic' id='' body=b'{"order_sn": "202208151537221205", "span_id": 18164471026988083044, "user_id...
                   └ <bound method OrderServicer.local_execute of <handler.order.OrderServicer object at 0x7ff10eae1910>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 207, in local_execute
    client = self._grpcClient(cfg["goods"]["name"], span)
             │    │           │                     └ 5de6ce15f34534a4:8a0f521925a68f6c:fc152a28d87fe764:1 order-dao.local_execute_goods
             │    │           └ {'name': 'order-dao', 'host': '192.168.8.222', 'port': 4347, 'consul': {'host': '192.168.8.222', 'port': 8500, 'tags': ['gpma...
             │    └ <function OrderServicer._grpcClient at 0x7ff10e745160>
             └ <handler.order.OrderServicer object at 0x7ff10eae1910>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 97, in _grpcClient
    span = ActiveSpanSource()
           └ <class 'common.grpc_opentracing.ActiveSpanSource'>

TypeError: Can't instantiate abstract class ActiveSpanSource with abstract method get_active_span
2022-08-15 15:38:23.436 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:38:23.436 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:38:23.436 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:38:29.846 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:38:29.846 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:38:29.846 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:38:32.769 | ERROR    | handler.order:local_execute:206 - An error has been caught in function 'local_execute', process 'MainProcess' (93526), thread 'ThreadPoolExecutor-0_0' (123145482059776):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f7a61fe9c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145482059776)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f7a61fe9940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145482059776)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145482059776)>
    │    │        │    └ (<weakref at 0x7f7a6590ac70; to 'ThreadPoolExecutor' at 0x7f7a6589feb0>, <_queue.SimpleQueue object at 0x7f7a658aaa90>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145482059776)>
    │    └ <function _worker at 0x7f7a658ad820>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145482059776)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f7a658adca0>
    └ <concurrent.futures.thread._WorkItem object at 0x7f7a659143a0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f7a659143a0>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f7a6590a900>, <grpc._server._RPCState object at 0x7f7a6589fa60>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f7a659143a0>
             │    └ <function _unary_response_in_pool at 0x7f7a658efca0>
             └ <concurrent.futures.thread._WorkItem object at 0x7f7a659143a0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7f7a65909b80>
                        │              │          └ <grpc._server._RPCState object at 0x7f7a6589fa60>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f7a6590a900>
                        └ <function _call_behavior at 0x7f7a658ef8b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f7a65914670>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7f7a65909b80>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 272, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7f7a658c1940>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7f7a6589fe50>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7f7a6589faf0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/_server.py", line 154, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7f7a65914910>
               │       └ user_id: 1
               │         name: "\346\256\265\350\266\205123"
               │         mobile: "18612917508"
               │         address: "\345\215\216\344\270\2551code"
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7f7a65909d30>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 269, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ user_id: 1
           │    │                   │             name: "\346\256\265\350\266\205123"
           │    │                   │             mobile: "18612917508"
           │    │                   │             address: "\345\215\216\344\270\2551code"
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7f7a6589faf0>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 149, in CreateOrder
    ret = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7f7a655458b0>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7f7a658e4970>
          │ │                           └ <rocketmq.client.Message object at 0x7f7a65914a00>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7f7a63c18a60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7f7a65914970>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 336, in send_message_in_transaction
    dll.SendMessageTransaction(self._handle,
    │   │                      │    └ 105553136104544
    │   │                      └ <rocketmq.client.TransactionMQProducer object at 0x7f7a65914970>
    │   └ <_FuncPtr object at 0x7f7a63c06e80>
    └ <CDLL '/usr/local/lib/librocketmq.dylib', handle 21ae99ce0 at 0x7f7a63ba9400>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 317, in _on_local_execute
    local_result = local_execute(py_message, usr_args)
                   │             │           └ None
                   │             └ <ReceivedMessage topic='transTopic' id='serializeTypeCurrentRPC":"JSON","version":373}' body=b'{"order_sn": "2022081515383218...
                   └ <bound method OrderServicer.local_execute of <handler.order.OrderServicer object at 0x7f7a658e4970>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 206, in local_execute
    client = self._grpcClient(cfg["goods"]["name"], span)
             │    │           │                     └ ac0348eb51faff77:18c904e97d17b769:4ae1b3a609acd7c9:1 order-dao.local_execute_goods
             │    │           └ {'name': 'order-dao', 'host': '192.168.8.222', 'port': 4347, 'consul': {'host': '192.168.8.222', 'port': 8500, 'tags': ['gpma...
             │    └ <function OrderServicer._grpcClient at 0x7f7a65545160>
             └ <handler.order.OrderServicer object at 0x7f7a658e4970>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 97, in _grpcClient
    span=parent_span.get_active_span()
         └ ac0348eb51faff77:18c904e97d17b769:4ae1b3a609acd7c9:1 order-dao.local_execute_goods

AttributeError: 'Span' object has no attribute 'get_active_span'
2022-08-15 15:38:32.769 | ERROR    | handler.order:local_execute:206 - An error has been caught in function 'local_execute', process 'MainProcess' (93526), thread 'ThreadPoolExecutor-0_0' (123145482059776):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f7a61fe9c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145482059776)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f7a61fe9940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145482059776)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145482059776)>
    │    │        │    └ (<weakref at 0x7f7a6590ac70; to 'ThreadPoolExecutor' at 0x7f7a6589feb0>, <_queue.SimpleQueue object at 0x7f7a658aaa90>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145482059776)>
    │    └ <function _worker at 0x7f7a658ad820>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145482059776)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f7a658adca0>
    └ <concurrent.futures.thread._WorkItem object at 0x7f7a659143a0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f7a659143a0>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f7a6590a900>, <grpc._server._RPCState object at 0x7f7a6589fa60>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f7a659143a0>
             │    └ <function _unary_response_in_pool at 0x7f7a658efca0>
             └ <concurrent.futures.thread._WorkItem object at 0x7f7a659143a0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7f7a65909b80>
                        │              │          └ <grpc._server._RPCState object at 0x7f7a6589fa60>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f7a6590a900>
                        └ <function _call_behavior at 0x7f7a658ef8b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f7a65914670>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7f7a65909b80>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 272, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7f7a658c1940>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7f7a6589fe50>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7f7a6589faf0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/_server.py", line 154, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7f7a65914910>
               │       └ user_id: 1
               │         name: "\346\256\265\350\266\205123"
               │         mobile: "18612917508"
               │         address: "\345\215\216\344\270\2551code"
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7f7a65909d30>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 269, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ user_id: 1
           │    │                   │             name: "\346\256\265\350\266\205123"
           │    │                   │             mobile: "18612917508"
           │    │                   │             address: "\345\215\216\344\270\2551code"
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7f7a6589faf0>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 149, in CreateOrder
    ret = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7f7a655458b0>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7f7a658e4970>
          │ │                           └ <rocketmq.client.Message object at 0x7f7a65914a00>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7f7a63c18a60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7f7a65914970>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 336, in send_message_in_transaction
    dll.SendMessageTransaction(self._handle,
    │   │                      │    └ 105553136104544
    │   │                      └ <rocketmq.client.TransactionMQProducer object at 0x7f7a65914970>
    │   └ <_FuncPtr object at 0x7f7a63c06e80>
    └ <CDLL '/usr/local/lib/librocketmq.dylib', handle 21ae99ce0 at 0x7f7a63ba9400>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 317, in _on_local_execute
    local_result = local_execute(py_message, usr_args)
                   │             │           └ None
                   │             └ <ReceivedMessage topic='transTopic' id='serializeTypeCurrentRPC":"JSON","version":373}' body=b'{"order_sn": "2022081515383218...
                   └ <bound method OrderServicer.local_execute of <handler.order.OrderServicer object at 0x7f7a658e4970>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 206, in local_execute
    client = self._grpcClient(cfg["goods"]["name"], span)
             │    │           │                     └ ac0348eb51faff77:18c904e97d17b769:4ae1b3a609acd7c9:1 order-dao.local_execute_goods
             │    │           └ {'name': 'order-dao', 'host': '192.168.8.222', 'port': 4347, 'consul': {'host': '192.168.8.222', 'port': 8500, 'tags': ['gpma...
             │    └ <function OrderServicer._grpcClient at 0x7f7a65545160>
             └ <handler.order.OrderServicer object at 0x7f7a658e4970>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 97, in _grpcClient
    span=parent_span.get_active_span()
         └ ac0348eb51faff77:18c904e97d17b769:4ae1b3a609acd7c9:1 order-dao.local_execute_goods

AttributeError: 'Span' object has no attribute 'get_active_span'
2022-08-15 15:38:32.769 | ERROR    | handler.order:local_execute:206 - An error has been caught in function 'local_execute', process 'MainProcess' (93526), thread 'ThreadPoolExecutor-0_0' (123145482059776):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f7a61fe9c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145482059776)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f7a61fe9940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145482059776)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145482059776)>
    │    │        │    └ (<weakref at 0x7f7a6590ac70; to 'ThreadPoolExecutor' at 0x7f7a6589feb0>, <_queue.SimpleQueue object at 0x7f7a658aaa90>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145482059776)>
    │    └ <function _worker at 0x7f7a658ad820>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145482059776)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f7a658adca0>
    └ <concurrent.futures.thread._WorkItem object at 0x7f7a659143a0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f7a659143a0>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f7a6590a900>, <grpc._server._RPCState object at 0x7f7a6589fa60>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f7a659143a0>
             │    └ <function _unary_response_in_pool at 0x7f7a658efca0>
             └ <concurrent.futures.thread._WorkItem object at 0x7f7a659143a0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7f7a65909b80>
                        │              │          └ <grpc._server._RPCState object at 0x7f7a6589fa60>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f7a6590a900>
                        └ <function _call_behavior at 0x7f7a658ef8b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f7a65914670>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7f7a65909b80>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 272, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7f7a658c1940>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7f7a6589fe50>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7f7a6589faf0>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/_server.py", line 154, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7f7a65914910>
               │       └ user_id: 1
               │         name: "\346\256\265\350\266\205123"
               │         mobile: "18612917508"
               │         address: "\345\215\216\344\270\2551code"
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7f7a65909d30>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 269, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ user_id: 1
           │    │                   │             name: "\346\256\265\350\266\205123"
           │    │                   │             mobile: "18612917508"
           │    │                   │             address: "\345\215\216\344\270\2551code"
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7f7a6589faf0>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 149, in CreateOrder
    ret = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7f7a655458b0>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7f7a658e4970>
          │ │                           └ <rocketmq.client.Message object at 0x7f7a65914a00>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7f7a63c18a60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7f7a65914970>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 336, in send_message_in_transaction
    dll.SendMessageTransaction(self._handle,
    │   │                      │    └ 105553136104544
    │   │                      └ <rocketmq.client.TransactionMQProducer object at 0x7f7a65914970>
    │   └ <_FuncPtr object at 0x7f7a63c06e80>
    └ <CDLL '/usr/local/lib/librocketmq.dylib', handle 21ae99ce0 at 0x7f7a63ba9400>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 317, in _on_local_execute
    local_result = local_execute(py_message, usr_args)
                   │             │           └ None
                   │             └ <ReceivedMessage topic='transTopic' id='serializeTypeCurrentRPC":"JSON","version":373}' body=b'{"order_sn": "2022081515383218...
                   └ <bound method OrderServicer.local_execute of <handler.order.OrderServicer object at 0x7f7a658e4970>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 206, in local_execute
    client = self._grpcClient(cfg["goods"]["name"], span)
             │    │           │                     └ ac0348eb51faff77:18c904e97d17b769:4ae1b3a609acd7c9:1 order-dao.local_execute_goods
             │    │           └ {'name': 'order-dao', 'host': '192.168.8.222', 'port': 4347, 'consul': {'host': '192.168.8.222', 'port': 8500, 'tags': ['gpma...
             │    └ <function OrderServicer._grpcClient at 0x7f7a65545160>
             └ <handler.order.OrderServicer object at 0x7f7a658e4970>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 97, in _grpcClient
    span=parent_span.get_active_span()
         └ ac0348eb51faff77:18c904e97d17b769:4ae1b3a609acd7c9:1 order-dao.local_execute_goods

AttributeError: 'Span' object has no attribute 'get_active_span'
2022-08-15 15:39:15.731 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:39:15.731 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:39:15.731 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:39:17.679 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:39:17.679 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:39:17.679 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:39:21.090 | ERROR    | grpc_opentracing.grpcext._interceptor:handler:269 - An error has been caught in function 'handler', process 'MainProcess' (93578), thread 'ThreadPoolExecutor-0_0' (123145420619776):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fb0c67cec10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145420619776)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fb0c67ce940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145420619776)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145420619776)>
    │    │        │    └ (<weakref at 0x7fb0c9b18d10; to 'ThreadPoolExecutor' at 0x7fb0c9aadee0>, <_queue.SimpleQueue object at 0x7fb0c9ab8ef0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145420619776)>
    │    └ <function _worker at 0x7fb0c9abb790>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145420619776)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fb0c9abbc10>
    └ <concurrent.futures.thread._WorkItem object at 0x7fb0c9b223a0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fb0c9b223a0>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fb0c9b189a0>, <grpc._server._RPCState object at 0x7fb0c9aada90>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fb0c9b223a0>
             │    └ <function _unary_response_in_pool at 0x7fb0c9afec10>
             └ <concurrent.futures.thread._WorkItem object at 0x7fb0c9b223a0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fb0c9b17790>
                        │              │          └ <grpc._server._RPCState object at 0x7fb0c9aada90>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fb0c9b189a0>
                        └ <function _call_behavior at 0x7fb0c9afe820>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fb0c9b226a0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fb0c9b17790>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 272, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7fb0c9acf8b0>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7fb0c9aade80>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fb0c9aadb20>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/_server.py", line 154, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7fb0c9b22910>
               │       └ user_id: 1
               │         name: "\346\256\265\350\266\205123"
               │         mobile: "18612917508"
               │         address: "\345\215\216\344\270\2551code"
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7fb0c9b17ca0>

> File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 269, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ user_id: 1
           │    │                   │             name: "\346\256\265\350\266\205123"
           │    │                   │             mobile: "18612917508"
           │    │                   │             address: "\345\215\216\344\270\2551code"
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fb0c9aadb20>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 148, in CreateOrder
    ret = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7fb0c9757820>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7fb0c9af2970>
          │ │                           └ <rocketmq.client.Message object at 0x7fb0c9b22a00>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7fb0c8518a60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7fb0c9b22970>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 335, in send_message_in_transaction
    ffi_check(
    └ <function ffi_check at 0x7fb0c85019d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/exceptions.py", line 44, in ffi_check
    raise exc_cls(msg)
          │       └ 'msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> li...
          └ <class 'rocketmq.exceptions.RocketMQException'>

rocketmq.exceptions.RocketMQException: msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> line:418,error:-1,in file </Users/shannon/work/OpenSource/Apache/rocketmq-client-cpp/src/producer/TransactionMQProducerImpl.cpp line:53
2022-08-15 15:39:21.090 | ERROR    | grpc_opentracing.grpcext._interceptor:handler:269 - An error has been caught in function 'handler', process 'MainProcess' (93578), thread 'ThreadPoolExecutor-0_0' (123145420619776):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fb0c67cec10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145420619776)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fb0c67ce940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145420619776)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145420619776)>
    │    │        │    └ (<weakref at 0x7fb0c9b18d10; to 'ThreadPoolExecutor' at 0x7fb0c9aadee0>, <_queue.SimpleQueue object at 0x7fb0c9ab8ef0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145420619776)>
    │    └ <function _worker at 0x7fb0c9abb790>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145420619776)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fb0c9abbc10>
    └ <concurrent.futures.thread._WorkItem object at 0x7fb0c9b223a0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fb0c9b223a0>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fb0c9b189a0>, <grpc._server._RPCState object at 0x7fb0c9aada90>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fb0c9b223a0>
             │    └ <function _unary_response_in_pool at 0x7fb0c9afec10>
             └ <concurrent.futures.thread._WorkItem object at 0x7fb0c9b223a0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fb0c9b17790>
                        │              │          └ <grpc._server._RPCState object at 0x7fb0c9aada90>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fb0c9b189a0>
                        └ <function _call_behavior at 0x7fb0c9afe820>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fb0c9b226a0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fb0c9b17790>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 272, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7fb0c9acf8b0>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7fb0c9aade80>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fb0c9aadb20>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/_server.py", line 154, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7fb0c9b22910>
               │       └ user_id: 1
               │         name: "\346\256\265\350\266\205123"
               │         mobile: "18612917508"
               │         address: "\345\215\216\344\270\2551code"
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7fb0c9b17ca0>

> File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 269, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ user_id: 1
           │    │                   │             name: "\346\256\265\350\266\205123"
           │    │                   │             mobile: "18612917508"
           │    │                   │             address: "\345\215\216\344\270\2551code"
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fb0c9aadb20>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 148, in CreateOrder
    ret = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7fb0c9757820>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7fb0c9af2970>
          │ │                           └ <rocketmq.client.Message object at 0x7fb0c9b22a00>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7fb0c8518a60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7fb0c9b22970>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 335, in send_message_in_transaction
    ffi_check(
    └ <function ffi_check at 0x7fb0c85019d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/exceptions.py", line 44, in ffi_check
    raise exc_cls(msg)
          │       └ 'msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> li...
          └ <class 'rocketmq.exceptions.RocketMQException'>

rocketmq.exceptions.RocketMQException: msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> line:418,error:-1,in file </Users/shannon/work/OpenSource/Apache/rocketmq-client-cpp/src/producer/TransactionMQProducerImpl.cpp line:53
2022-08-15 15:39:21.090 | ERROR    | grpc_opentracing.grpcext._interceptor:handler:269 - An error has been caught in function 'handler', process 'MainProcess' (93578), thread 'ThreadPoolExecutor-0_0' (123145420619776):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fb0c67cec10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145420619776)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fb0c67ce940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145420619776)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145420619776)>
    │    │        │    └ (<weakref at 0x7fb0c9b18d10; to 'ThreadPoolExecutor' at 0x7fb0c9aadee0>, <_queue.SimpleQueue object at 0x7fb0c9ab8ef0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145420619776)>
    │    └ <function _worker at 0x7fb0c9abb790>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145420619776)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fb0c9abbc10>
    └ <concurrent.futures.thread._WorkItem object at 0x7fb0c9b223a0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fb0c9b223a0>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fb0c9b189a0>, <grpc._server._RPCState object at 0x7fb0c9aada90>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fb0c9b223a0>
             │    └ <function _unary_response_in_pool at 0x7fb0c9afec10>
             └ <concurrent.futures.thread._WorkItem object at 0x7fb0c9b223a0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fb0c9b17790>
                        │              │          └ <grpc._server._RPCState object at 0x7fb0c9aada90>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fb0c9b189a0>
                        └ <function _call_behavior at 0x7fb0c9afe820>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fb0c9b226a0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fb0c9b17790>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 272, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7fb0c9acf8b0>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7fb0c9aade80>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fb0c9aadb20>

  File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/_server.py", line 154, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7fb0c9b22910>
               │       └ user_id: 1
               │         name: "\346\256\265\350\266\205123"
               │         mobile: "18612917508"
               │         address: "\345\215\216\344\270\2551code"
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7fb0c9b17ca0>

> File "/Users/www/learn-note/gpmall/daoServer/common/grpc_opentracing/grpcext/_interceptor.py", line 269, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ user_id: 1
           │    │                   │             name: "\346\256\265\350\266\205123"
           │    │                   │             mobile: "18612917508"
           │    │                   │             address: "\345\215\216\344\270\2551code"
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fb0c9aadb20>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 148, in CreateOrder
    ret = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7fb0c9757820>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7fb0c9af2970>
          │ │                           └ <rocketmq.client.Message object at 0x7fb0c9b22a00>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7fb0c8518a60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7fb0c9b22970>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 335, in send_message_in_transaction
    ffi_check(
    └ <function ffi_check at 0x7fb0c85019d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/exceptions.py", line 44, in ffi_check
    raise exc_cls(msg)
          │       └ 'msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> li...
          └ <class 'rocketmq.exceptions.RocketMQException'>

rocketmq.exceptions.RocketMQException: msg: No route info of this topic: transTopic,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp> line:418,error:-1,in file </Users/shannon/work/OpenSource/Apache/rocketmq-client-cpp/src/producer/TransactionMQProducerImpl.cpp line:53
2022-08-15 15:43:36.496 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:43:36.496 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:43:36.496 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:43:41.084 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:43:41.084 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:43:41.084 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:45:20.441 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:45:20.441 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:45:20.441 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:45:23.553 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:45:23.553 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:45:23.553 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:47:32.358 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:47:32.358 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:47:32.358 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:47:34.004 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:47:34.004 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:47:34.004 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-15 15:47:41.488 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:47:41.488 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-15 15:47:41.488 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
