2022-08-11 01:21:36.456 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:21:36.456 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:21:36.456 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:30:33.336 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:30:33.336 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:30:33.336 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:32:47.953 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:32:47.953 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:32:47.953 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:34:10.125 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:34:10.125 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:34:10.125 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:34:24.499 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:34:24.499 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:34:24.499 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:34:28.120 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 01:34:28.120 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 01:34:28.120 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 01:34:46.269 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:34:46.269 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:34:46.269 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:35:34.025 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 01:35:34.025 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 01:35:34.025 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 01:39:20.504 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:39:20.504 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:39:20.504 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:39:49.881 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 01:39:49.881 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 01:39:49.881 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 01:40:54.729 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:40:54.729 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:40:54.729 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:42:03.916 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 01:42:03.916 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 01:42:03.916 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 01:43:32.969 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:43:32.969 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:43:32.969 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 01:43:37.957 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 01:43:37.957 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 01:43:37.957 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 02:21:35.425 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 02:21:35.425 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 02:21:35.425 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 02:21:51.515 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 02:21:51.515 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 02:21:51.515 | INFO     | __main__:f:116 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 02:28:16.100 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 02:28:16.100 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 02:28:16.100 | INFO     | __main__:run:69 - service start...: 192.168.8.222:4347
2022-08-11 03:34:30.980 | INFO     | __main__:f:117 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 03:34:30.980 | INFO     | __main__:f:117 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 03:34:30.980 | INFO     | __main__:f:117 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 03:49:26.001 | INFO     | __main__:run:68 - service start...: 192.168.8.222:4347
2022-08-11 03:49:26.001 | INFO     | __main__:run:68 - service start...: 192.168.8.222:4347
2022-08-11 03:49:26.001 | INFO     | __main__:run:68 - service start...: 192.168.8.222:4347
2022-08-11 04:00:45.381 | INFO     | __main__:f:115 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 04:00:45.381 | INFO     | __main__:f:115 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 04:00:45.381 | INFO     | __main__:f:115 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 04:00:47.728 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-11 04:00:47.728 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-11 04:00:47.728 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-11 04:00:59.940 | ERROR    | grpc_opentracing.grpcext._interceptor:handler:267 - An error has been caught in function 'handler', process 'MainProcess' (78474), thread 'ThreadPoolExecutor-0_0' (123145489223680):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7ff2f45e8c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145489223680)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7ff2f45e8940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145489223680)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145489223680)>
    │    │        │    └ (<weakref at 0x7ff2f9408950; to 'ThreadPoolExecutor' at 0x7ff2f939e610>, <_queue.SimpleQueue object at 0x7ff2f93a7a90>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145489223680)>
    │    └ <function _worker at 0x7ff2f93ca160>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145489223680)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7ff2f93ca280>
    └ <concurrent.futures.thread._WorkItem object at 0x7ff2f94138b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7ff2f94138b0>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7ff2f94084f0>, <grpc._server._RPCState object at 0x7ff2f939e6d0>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7ff2f94138b0>
             │    └ <function _unary_response_in_pool at 0x7ff2f93edca0>
             └ <concurrent.futures.thread._WorkItem object at 0x7ff2f94138b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7ff2f9406af0>
                        │              │          └ <grpc._server._RPCState object at 0x7ff2f939e6d0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7ff2f94084f0>
                        └ <function _call_behavior at 0x7ff2f93ed8b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7ff2f9413a00>
                           │        └ id: 4
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7ff2f9406af0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc_opentracing/grpcext/_interceptor.py", line 270, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7ff2f93c8b80>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7ff2f939e460>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7ff2f9403700>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc_opentracing/_server.py", line 152, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7ff2f9413bb0>
               │       └ id: 4
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7ff2f9406b80>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc_opentracing/grpcext/_interceptor.py", line 267, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ id: 4
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7ff2f9403700>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 369, in QueryOrderDetail
    config = Config(

NameError: name 'Config' is not defined
2022-08-11 04:00:59.940 | ERROR    | grpc_opentracing.grpcext._interceptor:handler:267 - An error has been caught in function 'handler', process 'MainProcess' (78474), thread 'ThreadPoolExecutor-0_0' (123145489223680):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7ff2f45e8c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145489223680)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7ff2f45e8940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145489223680)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145489223680)>
    │    │        │    └ (<weakref at 0x7ff2f9408950; to 'ThreadPoolExecutor' at 0x7ff2f939e610>, <_queue.SimpleQueue object at 0x7ff2f93a7a90>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145489223680)>
    │    └ <function _worker at 0x7ff2f93ca160>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145489223680)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7ff2f93ca280>
    └ <concurrent.futures.thread._WorkItem object at 0x7ff2f94138b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7ff2f94138b0>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7ff2f94084f0>, <grpc._server._RPCState object at 0x7ff2f939e6d0>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7ff2f94138b0>
             │    └ <function _unary_response_in_pool at 0x7ff2f93edca0>
             └ <concurrent.futures.thread._WorkItem object at 0x7ff2f94138b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7ff2f9406af0>
                        │              │          └ <grpc._server._RPCState object at 0x7ff2f939e6d0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7ff2f94084f0>
                        └ <function _call_behavior at 0x7ff2f93ed8b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7ff2f9413a00>
                           │        └ id: 4
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7ff2f9406af0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc_opentracing/grpcext/_interceptor.py", line 270, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7ff2f93c8b80>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7ff2f939e460>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7ff2f9403700>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc_opentracing/_server.py", line 152, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7ff2f9413bb0>
               │       └ id: 4
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7ff2f9406b80>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc_opentracing/grpcext/_interceptor.py", line 267, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ id: 4
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7ff2f9403700>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 369, in QueryOrderDetail
    config = Config(

NameError: name 'Config' is not defined
2022-08-11 04:00:59.940 | ERROR    | grpc_opentracing.grpcext._interceptor:handler:267 - An error has been caught in function 'handler', process 'MainProcess' (78474), thread 'ThreadPoolExecutor-0_0' (123145489223680):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7ff2f45e8c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145489223680)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7ff2f45e8940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145489223680)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145489223680)>
    │    │        │    └ (<weakref at 0x7ff2f9408950; to 'ThreadPoolExecutor' at 0x7ff2f939e610>, <_queue.SimpleQueue object at 0x7ff2f93a7a90>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145489223680)>
    │    └ <function _worker at 0x7ff2f93ca160>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145489223680)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7ff2f93ca280>
    └ <concurrent.futures.thread._WorkItem object at 0x7ff2f94138b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7ff2f94138b0>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7ff2f94084f0>, <grpc._server._RPCState object at 0x7ff2f939e6d0>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7ff2f94138b0>
             │    └ <function _unary_response_in_pool at 0x7ff2f93edca0>
             └ <concurrent.futures.thread._WorkItem object at 0x7ff2f94138b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7ff2f9406af0>
                        │              │          └ <grpc._server._RPCState object at 0x7ff2f939e6d0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7ff2f94084f0>
                        └ <function _call_behavior at 0x7ff2f93ed8b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7ff2f9413a00>
                           │        └ id: 4
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7ff2f9406af0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc_opentracing/grpcext/_interceptor.py", line 270, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7ff2f93c8b80>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7ff2f939e460>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7ff2f9403700>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc_opentracing/_server.py", line 152, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7ff2f9413bb0>
               │       └ id: 4
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7ff2f9406b80>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc_opentracing/grpcext/_interceptor.py", line 267, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ id: 4
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7ff2f9403700>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 369, in QueryOrderDetail
    config = Config(

NameError: name 'Config' is not defined
2022-08-11 04:01:37.038 | INFO     | __main__:f:118 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 04:01:37.038 | INFO     | __main__:f:118 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 04:01:37.038 | INFO     | __main__:f:118 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 04:01:38.653 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-11 04:01:38.653 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-11 04:01:38.653 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-11 04:02:03.899 | ERROR    | grpc_opentracing.grpcext._interceptor:handler:267 - An error has been caught in function 'handler', process 'MainProcess' (78532), thread 'ThreadPoolExecutor-0_0' (123145587642368):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fba575e8c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145587642368)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fba575e8940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145587642368)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145587642368)>
    │    │        │    └ (<weakref at 0x7fba5ac479f0; to 'ThreadPoolExecutor' at 0x7fba5aaa2370>, <_queue.SimpleQueue object at 0x7fba5aae6a90>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145587642368)>
    │    └ <function _worker at 0x7fba5ac0b0d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145587642368)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fba5ac0b1f0>
    └ <concurrent.futures.thread._WorkItem object at 0x7fba5ac4f6d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fba5ac4f6d0>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fba5ac47e00>, <grpc._server._RPCState object at 0x7fba5ac3d7f0>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fba5ac4f6d0>
             │    └ <function _unary_response_in_pool at 0x7fba5ac2fd30>
             └ <concurrent.futures.thread._WorkItem object at 0x7fba5ac4f6d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fba5ac46af0>
                        │              │          └ <grpc._server._RPCState object at 0x7fba5ac3d7f0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fba5ac47e00>
                        └ <function _call_behavior at 0x7fba5ac2f940>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fba5ac4ff10>
                           │        └ id: 4
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fba5ac46af0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc_opentracing/grpcext/_interceptor.py", line 270, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7fba5ac07af0>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7fba5aadcfa0>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fba5aadcc40>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc_opentracing/_server.py", line 152, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7fba5ac68100>
               │       └ id: 4
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7fba5ac46dc0>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc_opentracing/grpcext/_interceptor.py", line 267, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ id: 4
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fba5aadcc40>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 382, in QueryOrderDetail
    with tracer.start_span("select_mysql",child_of=context.get_active_span()) as sel:
         │                                         │       └ <function _OpenTracingServicerContext.get_active_span at 0x7fba5ac07820>
         │                                         └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7fba5ac68100>
         └ None

AttributeError: 'NoneType' object has no attribute 'start_span'
2022-08-11 04:02:03.899 | ERROR    | grpc_opentracing.grpcext._interceptor:handler:267 - An error has been caught in function 'handler', process 'MainProcess' (78532), thread 'ThreadPoolExecutor-0_0' (123145587642368):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fba575e8c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145587642368)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fba575e8940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145587642368)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145587642368)>
    │    │        │    └ (<weakref at 0x7fba5ac479f0; to 'ThreadPoolExecutor' at 0x7fba5aaa2370>, <_queue.SimpleQueue object at 0x7fba5aae6a90>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145587642368)>
    │    └ <function _worker at 0x7fba5ac0b0d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145587642368)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fba5ac0b1f0>
    └ <concurrent.futures.thread._WorkItem object at 0x7fba5ac4f6d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fba5ac4f6d0>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fba5ac47e00>, <grpc._server._RPCState object at 0x7fba5ac3d7f0>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fba5ac4f6d0>
             │    └ <function _unary_response_in_pool at 0x7fba5ac2fd30>
             └ <concurrent.futures.thread._WorkItem object at 0x7fba5ac4f6d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fba5ac46af0>
                        │              │          └ <grpc._server._RPCState object at 0x7fba5ac3d7f0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fba5ac47e00>
                        └ <function _call_behavior at 0x7fba5ac2f940>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fba5ac4ff10>
                           │        └ id: 4
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fba5ac46af0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc_opentracing/grpcext/_interceptor.py", line 270, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7fba5ac07af0>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7fba5aadcfa0>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fba5aadcc40>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc_opentracing/_server.py", line 152, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7fba5ac68100>
               │       └ id: 4
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7fba5ac46dc0>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc_opentracing/grpcext/_interceptor.py", line 267, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ id: 4
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fba5aadcc40>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 382, in QueryOrderDetail
    with tracer.start_span("select_mysql",child_of=context.get_active_span()) as sel:
         │                                         │       └ <function _OpenTracingServicerContext.get_active_span at 0x7fba5ac07820>
         │                                         └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7fba5ac68100>
         └ None

AttributeError: 'NoneType' object has no attribute 'start_span'
2022-08-11 04:02:03.899 | ERROR    | grpc_opentracing.grpcext._interceptor:handler:267 - An error has been caught in function 'handler', process 'MainProcess' (78532), thread 'ThreadPoolExecutor-0_0' (123145587642368):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fba575e8c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145587642368)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fba575e8940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145587642368)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145587642368)>
    │    │        │    └ (<weakref at 0x7fba5ac479f0; to 'ThreadPoolExecutor' at 0x7fba5aaa2370>, <_queue.SimpleQueue object at 0x7fba5aae6a90>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145587642368)>
    │    └ <function _worker at 0x7fba5ac0b0d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145587642368)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fba5ac0b1f0>
    └ <concurrent.futures.thread._WorkItem object at 0x7fba5ac4f6d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fba5ac4f6d0>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fba5ac47e00>, <grpc._server._RPCState object at 0x7fba5ac3d7f0>, <functio...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fba5ac4f6d0>
             │    └ <function _unary_response_in_pool at 0x7fba5ac2fd30>
             └ <concurrent.futures.thread._WorkItem object at 0x7fba5ac4f6d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fba5ac46af0>
                        │              │          └ <grpc._server._RPCState object at 0x7fba5ac3d7f0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fba5ac47e00>
                        └ <function _call_behavior at 0x7fba5ac2f940>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fba5ac4ff10>
                           │        └ id: 4
                           │          
                           └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation at 0x7fba5ac46af0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc_opentracing/grpcext/_interceptor.py", line 270, in adaptation
    return self._interceptor.intercept_unary(
           │    │            └ <function OpenTracingServerInterceptor.intercept_unary at 0x7fba5ac07af0>
           │    └ <grpc_opentracing._server.OpenTracingServerInterceptor object at 0x7fba5aadcfa0>
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fba5aadcc40>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc_opentracing/_server.py", line 152, in intercept_unary
    response = handler(request, servicer_context)
               │       │        └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7fba5ac68100>
               │       └ id: 4
               │         
               └ <function _InterceptorRpcMethodHandler.unary_unary.<locals>.adaptation.<locals>.handler at 0x7fba5ac46dc0>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc_opentracing/grpcext/_interceptor.py", line 267, in handler
    return self._rpc_method_handler.unary_unary(request,
           │    │                   │           └ id: 4
           │    │                   │             
           │    │                   └ _tuplegetter(4, 'Alias for field number 4')
           │    └ RpcMethodHandler(request_streaming=False, response_streaming=False, request_deserializer=<built-in method FromString of Gener...
           └ <grpc_opentracing.grpcext._interceptor._InterceptorRpcMethodHandler object at 0x7fba5aadcc40>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 382, in QueryOrderDetail
    with tracer.start_span("select_mysql",child_of=context.get_active_span()) as sel:
         │                                         │       └ <function _OpenTracingServicerContext.get_active_span at 0x7fba5ac07820>
         │                                         └ <grpc_opentracing._server._OpenTracingServicerContext object at 0x7fba5ac68100>
         └ None

AttributeError: 'NoneType' object has no attribute 'start_span'
2022-08-11 04:05:43.581 | INFO     | __main__:f:118 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 04:05:43.581 | INFO     | __main__:f:118 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 04:05:43.581 | INFO     | __main__:f:118 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 04:11:48.764 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-11 04:11:48.764 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-11 04:11:48.764 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-11 04:14:27.894 | INFO     | __main__:f:118 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 04:14:27.894 | INFO     | __main__:f:118 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 04:14:27.894 | INFO     | __main__:f:118 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 04:14:55.212 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-11 04:14:55.212 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-11 04:14:55.212 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-11 04:15:25.163 | INFO     | __main__:f:118 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 04:15:25.163 | INFO     | __main__:f:118 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 04:15:25.163 | INFO     | __main__:f:118 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 04:15:47.662 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-11 04:15:47.662 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-11 04:15:47.662 | INFO     | __main__:run:71 - service start...: 192.168.8.222:4347
2022-08-11 04:16:22.970 | INFO     | __main__:f:118 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 04:16:22.970 | INFO     | __main__:f:118 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-11 04:16:22.970 | INFO     | __main__:f:118 - 退出订单服务 service stop...:192.168.8.222:4347
